### ISSUE TITLE
Pycapsule_new called with null pointer

### ISSUE THREAD

**Issue by leestamm** [3DFin/3DFin#59]
Hi!

please see uploaded Helicopter lidar in tall eucalypt forest. 
in order to upload i voxelised to 3cm.
it would be great if your plugin worked with this dataset. i am using from the latest cloudcompare v2.13.0

 3DFin failed with this error: 
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 70, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 570, in process
    self._export_stripe(clean_stripe)
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\cloudcompare\plugin_processing.py", line 114, in _export_stripe
    CloudComparePluginProcessing.write_sf(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\cloudcompare\plugin_processing.py", line 34, in write_sf
    sf_array = point_cloud.getScalarField(idx_sf).asArray()
ValueError: PyCapsule_New called with null pointer
[PNB118_GDA94_Lambert_AHD_CL -thinned_vox_3cm.zip](https://github.com/3DFin/3DFin/files/14291948/PNB118_GDA94_Lambert_AHD_CL.-thinned_vox_3cm.zip)

**Comment by Diegolainor** [comment]
Hi @leestamm, thanks a lot for using 3DFin! 

Please, can you upload a copy of the configuration file that was written by 3DFin in the output directory of the program? It should have a name similar to PNB118_GDA94_Lambert_AHD_CL -thinned_vox_3cm_config.ini. This way I can see the whole set of parameters that you are using.

Also, please, keep in mind that the software is designed to process ground-based point clouds. It could happen that no configuration of parameters can provide reliable results here due to relatively low point density, although we will try to find a configuration that suits your data :).

**Comment by leestamm** [comment]
HI,

Unfortunately, it appears that I removed the old config file accidentally since..
Therefore I don't have the old config file for this run sorry..

I could try again this week and have another go..

Regarding point density- you have a thinned version as the maximum upload was 28mb.. (6million points) the actual helicopter lidar is 70million points but I cannot transfer it to you unless you want to get it from a sharedrive.
I will replicate the issue and share a drive with you with the large file..

Regards

Lee Stamm | Senior Resource Analyst
Forestry Corporation of NSW | Planning

30 | Park Avenue | Coffs Harbour NSW 2450
PO Box 535 | Coffs Harbour NSW 2450
M: 0417 075 335 | E: ***@***.******@***.***> |
W: www.forestrycorporation.com.au<http://www.forestrycorporation.com.au/>
