### ISSUE TITLE
3DFin Runtime Error 

### ISSUE THREAD

**Issue by ashlynolah** [3DFin/3DFin#64]
Hi!
 3DFin failed with this error. I have enough memory on my PC, so I'm confused on why this isn't running. Also, I'm not sure why the CSV vile output would require so much data? I've included a link to my data below. It is a singular scan of a giant sequoia stem from ground level to about 5m up the tree obtained from mobile LiDAR. 

Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 70, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 625, in process
    ) = dm.compute_sections(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\sections.py", line 564, in compute_sections
    ) = fit_circle_check(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\sections.py", line 361, in fit_circle_check
    (X_g, Y_g) = point_clustering(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\sections.py", line 40, in point_clustering
    clust_id = sch.fclusterdata(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\scipy\cluster\hierarchy.py", line 2674, in fclusterdata
    Y = distance.pdist(X, metric=metric)
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\scipy\spatial\distance.py", line 2232, in pdist
    return pdist_fn(X, out=out, **kwargs)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 35.0 GiB for an array with shape (4702414731,) and data type float64

[SEGI Scan](https://drive.google.com/drive/folders/1gI2wpXHy1F5WerbHqB3qW4hFw-Jq__mw?usp=sharing)

**Comment by CaboCarlos** [comment]
3DFin is designed to deal with ground-based point clouds of forest plots and it gives results at the single tree level within said plot.
However, it should be able to process single trees if some basic conditions are met: there is enough ground (points on it) around the tree, the tree stem is adequately represented (covered with enough points), and the stem that is present is somehow taller than wider (3DFin asumes that tree stems are some kind of 'elongated' features' at certain scales). The case you uploaded is a point cloud with only points on the stem and the re`resentation of that stem reaches only a very low height compared to the diameter, and thre is not much terrain around the stem (compared to the diameter), so the algorithm struggles at seeing the elongated feature it is expecting and looking for... 
If, for example, you had the same point cloud, but with higher points, and a bit more context, you'd get some reults (although, as I said, it is not initially designed for it)

**Comment by CaboCarlos** [comment]
3DFin is designed to deal with terrestrial (any ground-based) point clouds of forest plots. Nevertheless, it could work with a single tree if the point cloud meets the conditions that the context of a full-plot dataset would give: enough terrain context (points covering enough terrain, so it can be modelled and the point cloud can be height-normalised), enough points on the stem, so the sections can be analysed, and enough representation of the stem (even if there are branches and/or understorey), so the stem can be identified as a 'rather elongated' feature..
The  case you upñoaded to ilustrate your question does not meet the terrain representation criterium, nor covers enough portion of the ste, so our algorithm can identified as the 'elongated' feature it is expecting and looking for...
