### ISSUE TITLE
3DFin failed with this error

### ISSUE THREAD

**Issue by srmazieg** [3DFin/3DFin#65]
Hi!
 3DFin failed with this error: 
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 70, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 497, in process
    z0_values = dm.normalize_heights(coords, dtm)
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\ground.py", line 233, in normalize_heights
    zs_diff_triples = cloud[:, 2] - np.average(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\numpy\lib\function_base.py", line 553, in average
    avg = avg_as_array = np.multiply(a, wgt,
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 6.24 GiB for an array with shape (279003485, 3) and data type float64

**Comment by rjanvier** [comment]
Hi, thanks for your report. 
You run out of memory, try to split you point cloud into smaller entities or pre-decimate it. You can also try to run 3DFin on a computer with a larger amount of RAM.

**Comment by srmazieg** [comment]
Thanks for your support. After a restart, it worked fine.

**Comment by rjanvier** [comment]
yes, it should help to free memory ;). have fun with 3DFin.

**Comment by rjanvier** [comment]
We added a better error message in such cases in 3DFin 0.4.0. It should be available in the next minor version of CC (2.14.2) to come in the coming weeks.
