### ISSUE TITLE
the program always gives me an error, how can I solve it?

### ISSUE THREAD

**Issue by mRossi97** [3DFin/3DFin#69]
### Hi everyone, I'm using the 3D forst inventory plugin to study an Italian forest in order to calculate the diameter and height of each tree. every time I try to calculate it I get the following error.
 _3DFin failed with this error: I tried to modify the input data but the result does not change. I would kindly like to know how to solve this problem so that I can complete my study. In the attachment I added some images of my cloud. thanks for your attention
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 70, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 524, in process
    clust_stripe = dm.verticality_clustering(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 238, in verticality_clustering
    clust_stripe, t = verticality_clustering_iteration(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 148, in verticality_clustering_iteration
    raise ValueError(
ValueError: Clusters were found, but they are too small to be considered potential stems using current settings. Suggestion: increase n points._
![Screenshot (155)](https://github.com/3DFin/3DFin/assets/171590367/c2936727-d458-46e4-bf46-1dc628df69f0)
![Screenshot (156)](https://github.com/3DFin/3DFin/assets/171590367/84c72f35-b723-4f09-94ea-a27c979fd486)

**Comment by Loris-L** [comment]
Hi. The end of error suggest you how to proceed: i see that your points cloud hasn't a high resolution, so you have to modify the advanced settings, particularly you could try to decrease number of voxel
