### ISSUE TITLE
3DFin Not Working

### ISSUE THREAD

**Issue by AIMSURVEYS** [3DFin/3DFin#73]
Hi!
 3DFin failed with this error: 
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 71, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 524, in process
    clust_stripe = dm.verticality_clustering(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 240, in verticality_clustering
    clust_stripe, t = verticality_clustering_iteration(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 150, in verticality_clustering_iteration
    raise ValueError(
ValueError: Clusters were found, but they are too small to be considered potential stems using current settings. Suggestion: increase n points.

What are n points?

The data looks good with clearly defined sterms.

**Comment by rjanvier** [comment]
Hi which version of 3DFin are you using (Standalone, CC plugin and version number). Thanks

**Comment by AIMSURVEYS** [comment]
Hi, Rjanvier

I am using the latest version of CC (1.13.2) latest stable release. 
Any help would be appreciated.

Thanks,

**Comment by rjanvier** [comment]
The error message is misleading but it should be fixed in next version. You could try to *decrease* `Maximum points` in expert tab to see if it solves your issue. I suggest to follow the [tutorial](https://github.com/3DFin/3DFin_Tutorial) and read  the documentation to be sure you understand the algorithm and its parameters to adapt to your specific dataset. if it does not help, do no hesitate to provide us your data if possible.

**Comment by AIMSURVEYS** [comment]
Hi Romain,

It may be that the data is not good enough. I have isolated a small section that has some trees clearly visible at the edges.

Please use the link below to download a small .BIN file.

https://ln5.sync.com/dl/876c0ed40/rudn3d2m-afz97yxu-7djf4ssd-wwbuir3r

**Comment by rjanvier** [comment]
HI. Sorry for the delay, I missed the last message, thanks for the data.I took a look at it, it seems not dense enough. Maybe @Diegolainor and @CaboCarlos infirm or confirm that.
