### ISSUE TITLE
Error 3Dfin

### ISSUE THREAD

**Issue by Camiladom1234** [3DFin/3DFin#75]
Hi!
 3DFin failed with this error: 
Traceback (most recent call last):
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\gui\application.py", line 71, in run
    self.processing_object.process()
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\three_d_fin\processing\abstract_processing.py", line 524, in process
    clust_stripe = dm.verticality_clustering(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 240, in verticality_clustering
    clust_stripe, t = verticality_clustering_iteration(
  File "C:\Program Files\CloudCompare\plugins\Python\Lib\site-packages\dendromatics\stripe.py", line 150, in verticality_clustering_iteration
    raise ValueError(
ValueError: Clusters were found, but they are too small to be considered potential stems using current settings. Suggestion: increase n points.

**Comment by rjanvier** [comment]
Hi. please see #73 for pointers. If nothing helps, could you please send us a sample of your data. thanks.
